---
name: IO-Async-Loop-Epoll
version: 0.07
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: use C<IO::Async> with C<epoll> on Linux
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  IO::Async::LoopTests: 0.24
  Test::More: 0
requires:
  IO::Async: 0.24
  IO::Epoll: 0.02
configure_requires:
  Module::Build: 0.35
provides:
  IO::Async::Loop::Epoll:
    file: lib/IO/Async/Loop/Epoll.pm
    version: 0.07
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
