---
name: IO-Async-Loop-Epoll
version: 0.02
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: a Loop using an C<IO::Epoll> object
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::Async: 0.17
  IO::Epoll: 0.02
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Refcount: 0
  Time::HiRes: 0
provides:
  IO::Async::Loop::Epoll:
    file: lib/IO/Async/Loop/Epoll.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
