---
abstract: 'use C<IO::Async> with C<epoll> on Linux'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::LoopTests: 0.24
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Async-Loop-Epoll
provides:
  IO::Async::Loop::Epoll:
    file: lib/IO/Async/Loop/Epoll.pm
    version: 0.09
requires:
  IO::Async: 0.24
  IO::Epoll: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
